{
  "comments": [
    {
      "key": {
        "uuid": "f459c4c1_8ccbff0e",
        "filename": "scripts/symbol.py",
        "patchSetId": 1
      },
      "lineNbr": 321,
      "author": {
        "id": 1003224
      },
      "writtenOn": "2018-08-10T15:24:04Z",
      "side": 1,
      "message": "does this mean there\u0027s no kind of error message in this case now?",
      "revId": "7fb53f5d2bfe4a112340da9c6daeefb10f9d9d1d",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "de51cb14_ef6f1583",
        "filename": "scripts/symbol.py",
        "patchSetId": 1
      },
      "lineNbr": 321,
      "author": {
        "id": 1043845
      },
      "writtenOn": "2018-08-10T16:35:21Z",
      "side": 1,
      "message": "Should probably logging.exception it before continuing. There isn\u0027t much to be done about it, but hiding the error could be confusing to the user.\n\nHow is `(None, None)` going to get displayed? Would it be better to use `(\u0027addr2line failed\u0027, str(ex))` or something?",
      "parentUuid": "f459c4c1_8ccbff0e",
      "revId": "7fb53f5d2bfe4a112340da9c6daeefb10f9d9d1d",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "4cf59990_c15c90fa",
        "filename": "scripts/symbol.py",
        "patchSetId": 1
      },
      "lineNbr": 321,
      "author": {
        "id": 1019050
      },
      "writtenOn": "2018-08-10T19:20:03Z",
      "side": 1,
      "message": "I modified the code so that the error shows up on the line that had the problem. I verified this by raising an IOError and seeing the error in the output.",
      "parentUuid": "de51cb14_ef6f1583",
      "revId": "7fb53f5d2bfe4a112340da9c6daeefb10f9d9d1d",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": true
    }
  ]
}